// examples/react-demo/src/App.jsx
import { useState, useEffect, useRef } from 'react'
import { Scheduler } from 'hyper-scheduler'

function App() {
  const [logs, setLogs] = useState([])
  const [isRunning, setIsRunning] = useState(false)
  const schedulerRef = useRef(null)

  const addLog = (msg) => {
    setLogs(prev => [`[${new Date().toLocaleTimeString()}] ${msg}`, ...prev].slice(0, 20))
  }

  useEffect(() => {
    schedulerRef.current = new Scheduler({ debug: true })
    
    schedulerRef.current.addTask({
      id: 'react-cron',
      schedule: '*/4 * * * * *',
      handler: () => addLog('React Cron Task (4s)')
    })

    schedulerRef.current.addTask({
      id: 'react-interval',
      schedule: '6s',
      handler: () => addLog('React Interval Task (6s)')
    })

    return () => {
      if (schedulerRef.current) {
        schedulerRef.current.stop()
      }
    }
  }, [])

  const toggle = () => {
    if (!schedulerRef.current) return
    
    if (isRunning) {
      schedulerRef.current.stop()
      addLog('Scheduler Stopped')
    } else {
      schedulerRef.current.start()
      addLog('Scheduler Started')
    }
    setIsRunning(!isRunning)
  }

  return (
    <div style={{ maxWidth: '600px', margin: '0 auto', padding: '2rem', fontFamily: 'sans-serif' }}>
      <h1>React Demo</h1>
      <div style={{ border: '1px solid #ccc', padding: '1rem', borderRadius: '8px' }}>
        <button 
          onClick={toggle}
          style={{ padding: '0.5rem 1rem', marginBottom: '1rem', cursor: 'pointer' }}
        >
          {isRunning ? 'Stop Scheduler' : 'Start Scheduler'}
        </button>
        <div style={{ background: '#f9f9f9', padding: '1rem', borderRadius: '4px', height: '200px', overflowY: 'auto', fontFamily: 'monospace' }}>
          {logs.map((log, index) => (
            <div key={index}>{log}</div>
          ))}
        </div>
      </div>
    </div>
  )
}

export default App

// examples/vue-demo/src/App.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { Scheduler } from 'hyper-scheduler'

const logs = ref<string[]>([])
const scheduler = ref<Scheduler | null>(null)
const isRunning = ref(false)

const addLog = (msg: string) => {
  logs.value.push(`[${new Date().toLocaleTimeString()}] ${msg}`)
  if (logs.value.length > 20) logs.value.shift()
}

onMounted(() => {
  scheduler.value = new Scheduler({ debug: true })
  
  // Cron Task
  scheduler.value.createTask({
    id: 'vue-cron',
    schedule: '*/3 * * * * *',
    handler: () => addLog('Vue Cron Task (3s)')
  })

  // Interval Task
  scheduler.value.createTask({
    id: 'vue-interval',
    schedule: '5s',
    handler: () => addLog('Vue Interval Task (5s)')
  })
})

onUnmounted(() => {
  if (scheduler.value) {
    scheduler.value.stop()
  }
})

const toggle = () => {
  if (!scheduler.value) return
  
  if (isRunning.value) {
    scheduler.value.stop()
    addLog('Scheduler Stopped')
  } else {
    scheduler.value.start()
    addLog('Scheduler Started')
  }
  isRunning.value = !isRunning.value
}
</script>

<template>
  <div class="container">
    <h1>Vue Demo</h1>
    <div class="card">
      <button @click="toggle">
        {{ isRunning ? 'Stop Scheduler' : 'Start Scheduler' }}
      </button>
      <div class="logs">
        <div v-for="(log, index) in logs" :key="index">{{ log }}</div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.container {
  max-width: 600px;
  margin: 0 auto;
  padding: 2rem;
  font-family: sans-serif;
}
.card {
  border: 1px solid #ccc;
  padding: 1rem;
  border-radius: 8px;
}
button {
  padding: 0.5rem 1rem;
  margin-bottom: 1rem;
  cursor: pointer;
}
.logs {
  background: #f9f9f9;
  padding: 1rem;
  border-radius: 4px;
  height: 200px;
  overflow-y: auto;
  font-family: monospace;
}
</style>
